version: '3.7'

services:
    web:
        build: ./src
        command: "python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./src:/usr/src/app
        ports:
            - "8000:8000"
        env_file:
            - ./.env.dev
        depends_on:
            - db
    db:
        image: postgres:13.3-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.dev

volumes:
    postgres_data:
