version: '3.7'

services:
    web:
        build: ./src
        command: "gunicorn core.wsgi:application --bind 0.0.0.0:8000"
        volumes:
            - static_volume:/usr/src/app/staticfiles
            - media_volume:/usr/src/app/media
        expose:
            - 8000
        env_file:
            - ./.env
        depends_on:
            - db
    db:
        image: postgres:13.3-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/usr/src/app/staticfiles
            - media_volume:/usr/src/app/media
        ports:
            - 1337:80
        depends_on:
            - web

volumes:
    postgres_data:
    static_volume:
    media_volume:
